# Site settings
title: Word Dolphin
description: Word Dolphin home page
baseurl: "/wds" # the subpath of your site, e.g. /blog
url: "https://michaelkazarian.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner Section
# hero: 112.jpg
hero-title: Word Dolphin
hero-description: Easy way to improve your foreign vocabulary
hero-video: NJMA0j9K8bQ

# Author - Creator
author-name: Word Dolphin
author-image: WordDolphinLogoCircle2.png
about-author: It's Word Dolphin, the app combines personal dictionary and word learning features. 
author-email: michael.kazarian@gmail.com
# author-twitter: https://twitter.com/
author-facebook: https://www.facebook.com/WordDolphin
# author-instagram: https://www.instagram.com/

# Other Authors - here you can add Other authors. For example Natali_Braxton
authors:
  Tetiana_Kazarian:
    author-name: Tetiana Kazarian
    author-image: TFoto.jpg
    about-author: I write articles about different things
    author-email: tatiana.kazarian@gmail.com
    author-facebook: https://www.facebook.com/kimkol.kimkol
    # author-instagram: https://www.instagram.com/
  Mykhailo_Kazarian:
    author-name: Mykhailo Kazarian
    author-image: MFoto.jpg
    about-author: Word Dolphin author
    author-email: michael.kazarian@gmail.com
    author-twitter: https://twitter.com/MykhailoKazari1
    author-facebook: https://www.facebook.com/mykhailo.kazarian.1
    # author-instagram: https://www.instagram.com/
    # author-pinterest: https://pinterest.com/

# Google Play site
google-play: https://play.google.com/store/apps/details?id=com.waverunner.wordrunner
    
# Social Media Links (Links are located in hero and footer)
# twitter: https://twitter.com/
facebook: https://www.facebook.com/WordDolphin
# google-plus: https://plus.google.com/
# instagram: https://www.instagram.com/
# pinterest: https://pinterest.com/
# youtube: https://www.youtube.com/

# Infobox (Social and subscribe)
infobox: false

# Contact Form Settings
contact-subtitle: Title for the subscription form.

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: pretty
paginate: 9
paginate_path: "/page/:num"

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

plugins:
  - jekyll-paginate
  - jekyll-feed

include:
  - _pages

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
